### ISSUE TITLE
Errors with null pointer exception

### ISSUE THREAD

**Issue by mtraton** [nordicway/a2pdf#1]
Exception in thread "main" java.lang.NullPointerException
    at it.zielke.a2pdf.Anki2PDF.main(Anki2PDF.java:129)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)

**Comment by nordicway** [comment]
Hi!
Thanks for the report. What is the location of your deck file? Does the file exist?

As a workaround If you don't have any images in your deck, you can comment that statement out.
