### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by intmainreturn00** [nordicway/a2pdf#2]
For some reason when parse my deck with images I've got this exception =(

owl$ java -jar a2pdf.jar /Users/owl/Downloads/a2pdf-0.2/android.apkg /Users/owl/Downloads/a2pdf-0.2/1.pdf
Base URI: file:////Users/owl/Downloads/a2pdf-0.2/
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
    at it.zielke.a2pdf.DeckFileParser.parseLine(DeckFileParser.java:60)
    at it.zielke.a2pdf.DeckFileParser.parse(DeckFileParser.java:51)
    at it.zielke.a2pdf.DeckFileParser.processDeck(DeckFileParser.java:43)
    at it.zielke.a2pdf.Anki2PDF.run(Anki2PDF.java:68)
    at it.zielke.a2pdf.Anki2PDF.main(Anki2PDF.java:133)

Can you recommend some work around ? 
Thanks for your tool btw =)

**Comment by nordicway** [comment]
You need to export the deck file as a text file.
